src/StockportContentApi/ContentfulFactories/ServicePayPaymentContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulServicePayPayment.cs
src/StockportContentApi/Controllers/ServicePayPaymentController.cs
src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Model/ServicePayPayment.cs
src/StockportContentApi/Repositories/ServicePayPaymentRepository.cs
test/StockportContentApiTests/Unit/Builders/ContentfulServicePayPaymentBuilder.cs
test/StockportContentApiTests/Unit/ContentfulFactories/ServicePayPaymentContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/Repositories/ServicePayPaymentRepositoryTest.cs

Add new ServicePayPayment content type and associated unit tests

feat(ServicePayPayment): add ServicePayPayment contentful type and associated unit tests

---

src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Program.cs
src/StockportContentApi/Services/HealthcheckService.cs
src/StockportContentApi/Startup.cs
src/StockportContentApi/StockportContentApi.csproj
src/StockportContentApi/Utils/CacheWrapper.cs
src/StockportContentApi/Utils/DistributedCacheWrapper.cs
src/StockportContentApi/Utils/SwaggerFilter.cs
src/StockportContentApi/web.config
test/StockportContentApiTests/LogTesting.cs
test/StockportContentApiTests/StockportContentApiTests.csproj
test/StockportContentApiTests/TestAppFactory.cs
test/StockportContentApiTests/Unit/Builders/ContentfulProfileBuilder.cs
test/StockportContentApiTests/Unit/Services/HealthcheckServiceTest.cs
test/StockportContentApiTests/Unit/Utils/CacheWrapperTest.cs

- Included small refactor of DistrbutedCacheWrapper to use DistrbuteCache redis or inmemory packages.
- Removed Kestrel, leftover from older project infrastructure?
- Removed Some unused endpoints within DistrbutedCacheWrapper 
- Inmemory and unit test all passing

feat(DIGITAL-5670): net5.0 upgrade

---

src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs

Changes:
- fix for distributed Cache, Registered IDistributedCacheWrapper which was missed during net5 upgrade :(

fix(Startup): Register IDistributedCacheWrapper

---

test/StockportContentApiTests/Unit/Repositories/RedirectsRepositoryTest.cs

-Add unit test for GetRedirect
-Add unit test for GetUpdatedRedirect

test(redirect) add unit test for getredirect and getupdatedredirect

---

src/StockportContentApi/ContentfulFactories/ArticleFactories/ArticleContentfulFactory.cs
test/StockportContentApiTests/Unit/Builders/ContentfulArticleBuilder.cs
test/StockportContentApiTests/Unit/Builders/ContentfulSectionBuilder.cs
test/StockportContentApiTests/Unit/ContentfulFactories/ArticleContentfulFactoryTest.cs

Add functionality that enables the 'UpdateAt' Article property to be modified when any Section contained within has changes

6844: Date on articles

---

src/StockportContentApi/ContentfulFactories/HomepageContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulHomepage.cs
src/StockportContentApi/Model/CarouselContent.cs
src/StockportContentApi/Model/Homepage.cs
src/StockportContentApi/ResponseHandler.cs
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/Homepage.json
test/StockportContentApiTests/Unit/Builders/ContentfulHomepageBuilder.cs
test/StockportContentApiTests/Unit/Repositories/HomepageRepositoryTest.cs
test/StockportContentApiTests/Unit/ResponseHandlerTest.cs

* Add new CampaignBanner property to Homepage Model using CarouselContent Model
* Update unit tests

feat(Homepage): add CampaignBanner to Homepage

---

src/StockportContentApi/StockportContentApi.csproj
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/PrivacyNotice.json
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/Topic.json
test/StockportContentApiTests/StockportContentApiTests.csproj

This fixes route test failiure on team city

Fixed Route tests and upgraded deprecated package

---

src/StockportContentApi/ContentfulFactories/TopicFactories/TopicContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulTopic.cs
src/StockportContentApi/Model/CallToAction.cs
src/StockportContentApi/Model/Link.cs
src/StockportContentApi/Model/Topic.cs
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/PrivacyNotice.json
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/Topic.json

Added Link as C#9 record for convenience
Added CallToAction as C#9 record for convenience, with a Link
Added new property CallToAction to Topic

feat(CallToAction): add new property for Topic

---

src/StockportContentApi/ContentfulFactories/CallToActionContentfulFactory.cs
src/StockportContentApi/ContentfulFactories/TopicFactories/TopicContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulCallToAction.cs
src/StockportContentApi/ContentfulModels/ContentfulTopic.cs
src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Model/CallToAction.cs
src/StockportContentApi/Model/Link.cs
test/StockportContentApiTests/Unit/ContentfulFactories/TopicContentfulFactoryTest.cs

need to retrieve an image now for this call to action to bring it inline with Stockport Gov... used the DTO and Factory patterns for this.

fix(Call_To_Action): use dto and factory for image

---

src/StockportContentApi/ContentfulFactories/TopicFactories/TopicContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulTopic.cs
src/StockportContentApi/Model/Topic.cs
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/PrivacyNotice.json
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/Topic.json
test/StockportContentApiTests/Unit/Builders/ArticleBuilder.cs
test/StockportContentApiTests/Unit/Repositories/TopicRepositoryTest.cs

Jira Card - Events by tag to be pulled though to topic page
-) Add new property 'Tag' to retrieve events by tag
Checklist

Get events by category

---

src/StockportContentApi/ContentfulFactories/TopicFactories/TopicContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulTopic.cs
src/StockportContentApi/Model/Topic.cs
src/StockportContentApi/Model/TriviaSection.cs
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/PrivacyNotice.json
test/StockportContentApiTests/Integration/ExpectedContentApiResponses/Topic.json

Add a Trivia Section to a Topic

feat(TriviaSection): add to Topic

---

src/StockportContentApi/ContentfulFactories/EventFactories/EventHomepageContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulEventHomepage.cs
src/StockportContentApi/Model/EventHomepage.cs

Jira Card - Allow Alerts on the events home page (8768)
-) Add Alerts property in EventHomepage and Contentful model
Checklist

chore(model): Add Alerts property

---

src/StockportContentApi/ContentfulFactories/AlertContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulAlert.cs
src/StockportContentApi/Controllers/HomepageController.cs
src/StockportContentApi/Models/Alert.cs
test/StockportContentApiTests/Unit/Builders/AlertBuilder.cs
test/StockportContentApiTests/Unit/Builders/ArticleBuilder.cs
test/StockportContentApiTests/Unit/Builders/EventBuilder.cs
test/StockportContentApiTests/Unit/Builders/GroupBuilder.cs
test/StockportContentApiTests/Unit/ContentfulFactories/EventContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/ContentfulFactories/GroupHomepageContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/ContentfulFactories/HomepageContentfulFactoryTests.cs
test/StockportContentApiTests/Unit/ContentfulFactories/SectionContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/ContentfulFactories/ShowcaseContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/ContentfulFactories/TopicContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/Repositories/ArticleRepositoryTest.cs
test/StockportContentApiTests/Unit/Repositories/EventRepositoryTest.cs
test/StockportContentApiTests/Unit/Repositories/NewsRepositoryTest.cs
test/StockportContentApiTests/Unit/Repositories/ProfileRepositoryTest.cs
test/StockportContentApiTests/Unit/Repositories/ShowcaseRepositoryTest.cs
test/StockportContentApiTests/Unit/Repositories/StartPageRepositoryTest.cs
test/StockportContentApiTests/Unit/Repositories/TopicRepositoryTest.cs

Update to add Image reference alert model.

feat(): add functionality for condolenceBanner

---

.gitignore
Makefile
src/StockportContentApi/ContentfulFactories/CallToActionBannerContentfulFactory.cs
src/StockportContentApi/ContentfulFactories/HomepageContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulCallToActionBanner.cs
src/StockportContentApi/ContentfulModels/ContentfulHomepage.cs
src/StockportContentApi/Controllers/CommsController.cs
src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Models/CallToActionBanner.cs
src/StockportContentApi/Models/Homepage.cs
test/StockportContentApiTests/StockportContentApiTests.csproj
test/StockportContentApiTests/Unit/ContentfulFactories/CallToActionBannerContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/ContentfulFactories/CallToActionContentFactoryTest.cs
test/StockportContentApiTests/Unit/ContentfulFactories/HomepageContentfulFactoryTests.cs
test/StockportContentApiTests/Unit/Repositories/HomepageRepositoryTest.cs

feat(CTA): update models to accommodate CTA

---

src/StockportContentApi/ContentfulFactories/HomepageContentfulFactory.cs
src/StockportContentApi/ContentfulFactories/SpotlightOnBannerContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulHomepage.cs
src/StockportContentApi/ContentfulModels/ContentfulSpotlightOnBanner.cs
src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Models/Homepage.cs
src/StockportContentApi/Models/SpotlightOnBanner.cs
test/StockportContentApiTests/Unit/ContentfulFactories/HomepageContentfulFactoryTests.cs
test/StockportContentApiTests/Unit/ContentfulFactories/SpotlightOnBannerContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/Repositories/HomepageRepositoryTest.cs

- Add SpotlightOn Models
- Add SpotlightOn Factories
- Update Homepage model
- Add and Fix existing tests

feat(spotlightOn): add functionality to enable spotlight on

---

src/StockportContentApi/ContentfulFactories/StartPageFactoryContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulStartPage.cs
test/StockportContentApiTests/Unit/Builders/ContentfulStartPageBuilder.cs

Fixes issue with start pages throwing exception when a Background Issue is added.

Start page fix

---

src/StockportContentApi/ContentfulFactories/TopicFactories/TopicContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulTopic.cs
src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Models/Topic.cs
test/StockportContentApiTests/Unit/Builders/ArticleBuilder.cs
test/StockportContentApiTests/Unit/ContentfulFactories/TopicContentfulFactoryTest.cs
test/StockportContentApiTests/Unit/Repositories/TopicRepositoryTest.cs

* need to change CallToAction to CallToActionBanner in contentful for HS

fix(CTA): fix CTA for HealthyStockport

---

src/StockportContentApi/ContentfulModels/ContentfulReference.cs
src/StockportContentApi/Models/Filter.cs

- Add Highlight bool property to Filter model.

chore(filter): add highlight property to model

---

src/StockportContentApi/Middleware/AuthenticationMiddleware.cs
src/StockportContentApi/Program.cs
src/StockportContentApi/app-config/appsettings.int.json

Revert file secrets and add more logging - checking loaded env value

patch: revert secrets and add more logging in startup

---

src/StockportContentApi/ContentfulFactories/ContentBlockContentfulFactory.cs

- remove TriviaCardsScreenWidth
- rename TriviaCardsContentWidth to TriviaCards
- add check for background image

chore(ContentBlockContentfulFactory): rename trivia cards type + add check for background image

---

src/StockportContentApi/ContentfulFactories/ArticleFactories/ArticleContentfulFactory.cs
src/StockportContentApi/ContentfulFactories/EventFactories/EventContentfulFactory.cs
src/StockportContentApi/ContentfulFactories/ProfileContentfulFactory.cs
src/StockportContentApi/ContentfulModels/ContentfulArticle.cs
src/StockportContentApi/ContentfulModels/ContentfulEvent.cs
src/StockportContentApi/Controllers/EventController.cs
src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Factories/EventRecurrenceFactory.cs
src/StockportContentApi/Models/Event.cs
src/StockportContentApi/Models/Group.cs
src/StockportContentApi/Repositories/EventCategoryRepository.cs
src/StockportContentApi/Repositories/EventRepository.cs
test/StockportContentApiTests/Unit/Builders/EventBuilder.cs
test/StockportContentApiTests/Unit/ContentfulFactories/ArticleContentfulFactoryTests.cs
test/StockportContentApiTests/Unit/Repositories/ArticleRepositoryTests.cs
test/StockportContentApiTests/Unit/Repositories/ShowcaseRepositoryTests.cs

+ inlineQuote field on articles

chore(Event): add Duration and Languages fields

---

src/StockportContentApi/ContentfulFactories/ArticleFactories/ArticleContentfulFactory.cs
src/StockportContentApi/Controllers/ArticleController.cs
src/StockportContentApi/Extensions/ServiceCollectionExtensions.cs
src/StockportContentApi/Models/Article.cs
src/StockportContentApi/Repositories/ArticleRepository.cs
src/StockportContentApi/Repositories/LandingPageRepository.cs
test/StockportContentApiTests/Unit/Builders/ContentfulArticleBuilder.cs
test/StockportContentApiTests/Unit/Repositories/ArticleRepositoryTests.cs
test/StockportContentApiTests/Unit/Repositories/LandingPageRepositoryTests.cs

improvement to get events using multiple tags or categories -> stockroom and stockportgov
improvement to get news item using multiple tags or categories -> stockportgov only

chore(Article): add AssociatedTagOrCategory and Events fields
